language: java

jdk:
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: IX1gHNU2Xj+NVlyxrI4PZwOJMR1U83wn3h4mkdJ4BWETb1WvtaO1+9xaAf8J2EvtbjUKMBo6/1E55k1Q+xUULsbKD2I2UWBQ5EpIvPLXDAjKsiPbfKvTb4azDnvzDOARnHFkQPMJDgC/2+L3SDNsZlOvmsVlTDfUplu8uJRhUnBLYp2PJf8ASqOxlhryGAEKtuaDu+cBuGaKagz1EbIMG+5zur3+CfhxdckMKS71nx71tAfc3gQIRRa9Ey4qFGFRs0IzBDFDOPYHnk5jZ0rTK2kb5WcKtC8MNWYJlQk3WCo4bA3scWmQaDvjHGpDM1PaIKliVpJaxmfMRr7Y3Mx1Cs8oZd+xyX7cJrFGZbh+8LiqORovEcVPV6XaXeqbnvNm1JMsPOui0h9zPZ33v7IKgfFTU1vJl6LzcnsxTyvmlQq/okQls0H3+6pXm7dm0Xrr2V8WmpL/qLpTuldoMOLLc2jjJinbeqL6+QUG6SH+L96QlQHqqWFbvbYbdtTxn/hG+jyUEKpOCgw11JouYcRUDmKeqEQ7OMzfboZpxRPbz/qXdX1k0X+rOPj/zTc5VXLuH36JJDaDhpXjbcmGdh9oDvtLWQPTcKVvPm6zP/l2IuG2l1INGkfqM/osaH4axB98khFar00UnjjcXaONRzjyAXIcQ4ei8UWy1x/nfCRb8Yk=
    - secure: q1RIvSS5z9C98kE6BJPGjcaLseayVeBxHYUkZMHMPnacjDsEvxljVRr3Vx5dNS02SLqurdKxhbWC02v9LdN3PG/JZAyTCaE9Y8riMJWKLtY17YzX0JVg5kTe3wa83yKfVQHw6laYrwQRrNRtzO4AbBfyfm0KnGfORzo+wxCIxQAK6FjRDT8h5tnLYGJRthVUrZ8eQwNVhKS5Cq5HVpQ7HLPHai4q0xyVCcsCwiyFICChz/XJur8dY8oLz+vIb8vo8tVrVXwXrm4mP8LYXyh58LFb+ai5ISwEEm3L4r7hAaY8/3sFaojcCmTqxwBxi+Vp9BteCZepihaCHGVf28Lb6z1Bf8yTWdHWAs02JgaFQEBoFb+lAqXNORF5did5rEojZo8taSpDcedwAuOAMppvCkKJeu7bg6kfFau4r3vBYN2ZSq21plaHl+wCrShID+NXOtYjfwgvK+01qd5nDRUGoZwC3vHwSJhRhsONlVThbGOKMRZn+aF8YX2P3I0SiWuuuS4KBKss1YHfD9rSUQMzZ69EwxvzgwnWFWJFYclWF6EvCZATBPebXwfvqwGoSYKO0U3ZvbrgE9iycHO0MU+VXOmxBIId3NPpe6PAFkkLZT49pSGX+HNirql312cFurWAamy/t0yn6eexIIOmbSvTxyNiHFnKUrwLmSL6PYThc6Q=
